[YouTubeUi] Update to fix crash on DreamOS image when not detected langauge
  File /usr/lib/enigma2/python/Plugins/Extensions/YouTube/YouTubeUi.py, line 58, in <module>
    default=language.getLanguage().split('_')[1] if language.getLanguage().split('_')[1] != 'EN' else '',
-------
IndexError: list index out of range